meta_product_name: "Homuch"
meta_title: "Homuch - Estimate any Real Estate Asset"
meta_description: "Instant. Free. Accurate."
meta_image: "cover.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards



