meta_product_name: "Homuch"
meta_title: "Homuch - estimate assets' worth in a less than a minute !"
meta_description: "Quickly find out the right price for your next acquisition  "
meta_image: "homuch-color.png" # should exist in `app/assets/images/`
